name: Periodic Health Check

on:
  schedule:
    - cron: "59 23 * * *"

jobs:
  health_check:
    runs-on: ubuntu-latest
    steps:
      - name: URL Health Check
        uses: Jtalk/url-health-check-action@v4
        with:
          url: https://fullstack-open-part-11-kannvess.koyeb.app/
